default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: travel_booking_backend_development
test:
  <<: *default
  database: travel_booking_backend_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
